.PHONY: build run test clean

build:
	mvn clean package

run:
	mvn spring-boot:run

test:
	mvn test

clean:
	mvn clean

install:
	mvn install

help:
	@echo "Available commands:"
	@echo "  make build  - Build the application"
	@echo "  make run    - Run the application"
	@echo "  make test   - Run tests"
	@echo "  make clean  - Clean build artifacts" 